apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        {}
        # revision: HEAD
        # repoURL: https://github.com/ecoma-io/common-infras.git
        # directories:
        #   - path: src/core/*/prod
  template:
    metadata:
      name: "{{ index .path.segments 2 }}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: ""
        targetRevision: ""
        path: "{{ .path.path}}"
      destination:
        name: "in-cluster"
        namespace: "{{ index .path.segments 2 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
        retry:
          limit: 10
          backoff:
            duration: 1s
            factor: 2
            maxDuration: 5m
