apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: http
  namespace: cilium
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 0.0.0.0
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
